# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='trips_going_on',
            field=models.ManyToManyField(related_name='users_going_on', to='python_final.Trip'),
        ),
    ]
