# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_final', '0002_auto_20180720_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trips_going_on',
            field=models.ManyToManyField(related_name='users_on_trip', to='python_final.Trip'),
        ),
    ]
